stages:
  - build
  - push
  - release

variables:
  STORAGE_DRIVER: "vfs"
  ARTIFACT_DIR: "./arts"
  ARTIFACT_NAME: "blreserver-built-image.tar"

build-image:
  stage: build
  image:
    name: quay.io/buildah/stable:v1.27.0
  tags:
    - docker
  script:
    - buildah bud -f Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - mkdir ${ARTIFACT_DIR}
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME docker-archive:${ARTIFACT_DIR}/${ARTIFACT_NAME}:$CI_COMMIT_REF_NAME
  artifacts:
    name: "archive:${ARTIFACT_NAME}:${CI_JOB_ID}"
    when: "on_success"
    expire_in: "6h"
    paths:
      - ${ARTIFACT_DIR}/

push:
  stage: "push"
  image:
    name: quay.io/buildah/stable:v1.27.0
  script:
    - buildah pull docker-archive:${ARTIFACT_DIR}/${ARTIFACT_NAME}
    - echo $CI_REGISTRY_PASSWORD | buildah login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  dependencies:
    - build

tag-latest:
  stage: release
  only:
    - /^.*-release$/
  image:
    name: quay.io/buildah/stable:v1.27.0
  script:
    - buildah pull docker-archive:${ARTIFACT_DIR}/${ARTIFACT_NAME}
    - echo $CI_REGISTRY_PASSWORD | buildah login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - buildah push $CI_REGISTRY_IMAGE:latest
  dependencies:
    - build